### ISSUE TITLE
Some bugs discovered

### ISSUE THREAD

**Issue by corel67** [AJMix/TownOfImpostors#12]
Hello,

This mod is just amazing, it's a pleasure to discover all these new roles !

I just report some bugs I noticed during my games:

- It seems that it is possible to press the "shoot" button as Sheriff during the meetings. The shot targets the nearest character.
- On Polus, there is no Medbay zone. So the doctor can't reanimate someone if you activate the option. Is it possible to define an area as medbay in Polus?
- When the option to make crewmates anonymous during communication sabotage is activated, and a meeting is triggered during sabotage, the pets appear after the meeting (while the crewmates remain anonymous as long as the sabotage is not set).

Hopefully this can help you to improve this mod even more.

**Comment by Darkbrussel** [comment]
Hello corel67

Thank you for reporting these bugs, and glad to hear that you're enjoying this mod 😃 

We'll make sure these bugs will be looked into and probably fixed for the next patch of the mod 😄 

Kind Regards,

**Comment by AJMix** [comment]
Hi corel67,

Thanks for playing and trying the mod. Appreciate the really clear and concise explanation of each bug. These bugs have been fixed and will be pushed in the next release.

I'll close this issue once the next release is out. As always, feel free to reach out any time to report any further bugs or if you have any suggestions for changes👍

**Comment by corel67** [comment]
Thank you for the feedback and glad to hear that these reports were used.
I'll be sure to report if I see any more bugs.
Keep up the good work, it is really appreciated.

**Comment by AJMix** [comment]
Issues mentioned here have all been fixed in 1.6.0

Closing this issue 👍
