### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Snail09** [AJMix/TownOfImpostors#13]
I was playing a bit today and ran into some bugs, I've said a few of them to Dark, but I figured i'd put them here aswell

When playing as an arsonist, there is a bug similar to the sheriff bug detailed in yesterday's report where they can douse people during meetings when close to them
When you have a pet, and change from someone else to yourself inside of a vent, your pet appears ontop of the vent.
This is all that is (Possibly) new/not on another report for now, i'll comment on here if i find any more
You guys did a really good job on this, I hope you have fun with updating it, Have a nice day

**Comment by Darkbrussel** [comment]
Hey again Snail09

Thanks for playing the mod and describing these bugs in detail. really appreciate it. These bugs have been fixed and will be pushed in the next release.

Your feedback is appreciated.

Kind Regards,

**Comment by AJMix** [comment]
Hi Snail,

Thanks for reporting these bugs, I've fixed these issues and the changes will be in the 1.6 release

As always, I'll close this ticket as resolved once 1.6 is released

Cheers

**Comment by AJMix** [comment]
Issues reported here have all been fixed in 1.6.0

Closing this issue 👍
