### ISSUE TITLE
Let Jester fix sabotages, don't let Impostors vent with bodies & add Revive time

### ISSUE THREAD

**Issue by Arxareon** [AJMix/TownOfImpostors#14]
Hey!

Tanks for the mod, great one!
I wanted to leave feedback on some smaller things we noticed where there is potential for improvement when playing with friends tonight (thanks for hopping in and saying hi on Twitch btw ♥).

- **Let the Jester fix sabotages.** There are instances where you'd want to do it, especially near the end where you also lose if you don't do the sabotage. This could be included as an option, but I think it could just be the case by default. The Jester could decide whether to fix the sabotage or not in the match. (I'm not sure if the Arsonist can fix sabotages, they should be able to do so as well).
- **Do not let Impostors vent with the dead bodies.** Now, they can pick up a body, vent to a different place, drop it and vent back. This is too powerful. We'd want to let them drag and dispose of bodies, but if they can vent with them, that's too much. One way this could be addressed is making the Impostor drop the body next to the vent when they hop into it. If they want to dispose of it to that vent, they could hop out and do so, expending their cooldown on it. If they want to move it to a different room, they'll need to walk with the body all the way there without using vents. If some prefer the way it is, this could be implemented as an optional feature.
- **Add an optional channel time to the Revive ability of Doctors.** This could function similarly to the Arsonist's Douse time. Revive would not work instantly, instead the Doctor would need to stand next to the body for a specified amount of time. If set to 0 seconds, the Revive would be instant as it is now.

Thanks again, and have a nice day!

**Comment by AJMix** [comment]
Hi Arxareon,

Thanks for playing the mod and appreciate the feedback along with the clear & concise points!

The Jester and Arsonist being unable to fix sabotages was actually unintended and this is a bug that will be addressed in the release of 1.6, it'll be coming as custom options so you can enable whether Jester and Arsonist can fix sabotages or not.

The suggestions for Impostors and Doctors are great and others have given similar feedback too so there is definitely a general consensus for this and can be looked into as additional custom options that I'll try to get into the 1.6 release.

Best

**Comment by Arxareon** [comment]
Awesome! Thanks for the response, I'm glad to hear. :)

Cheers!
