### ISSUE TITLE
Suggestion list from others

### ISSUE THREAD

**Issue by Darkbrussel** [AJMix/TownOfImpostors#15]
They want some more visual indication for Doctor when healing, when the healing with timer is turned on. Such as a bar or some visual effect on the body you're reviving. 

Also there was a suggestion to make Jester a more lighter pink, for sake of syncing color with other mods to make it less confusing for those who have played other mods. And some do want to keep the purple, totally up to you AJ

**Comment by AJMix** [comment]
Suggestions implemented in 1.7.0

Closing
