### ISSUE TITLE
Impostor Morph carries over to Meetings.

### ISSUE THREAD

**Issue by C4KEfromSP4C3** [AJMix/TownOfImpostors#16]
I'm not sure what entirely caused this issue, whether it was immediately morphing and a meeting being called/body being reported however one of the players playing who was morphed as someone else appeared in the meeting with the same cosmetics as the player they morphed into.

**Comment by AJMix** [comment]
Hey C4KE,

Thanks for playing the mod. Not sure what could have caused this, but disguising issues with meetings are being looked into and will hopefully be fixed in the next release.

Best

**Comment by AJMix** [comment]
Issue appears to be fixed in 1.6.1. Please feel free to open another issue if this occurs again

Closing issue 👍
