### ISSUE TITLE
testing bans me from my impostor server

### ISSUE THREAD

**Issue by epicwappy20** [AJMix/TownOfImpostors#17]
it bans me when i join the game

**Comment by JonyKasual** [comment]
I imagine the client calls made in this mod will straight up look like cheating (and a subsequent ban) to the AntiCheat of that private server. You'll have to disable the server-sided AntiCheat to allow for that.

Please modify and save these Impostor server's config.json values to this for now:
```
  "AntiCheat": {
    "Enabled": false,
    "BanIpFromGame": false
  }
```

Then you'll have to take it up with the Impostor team on some way for the AntiCheat to consider mods.

**Comment by JonyKasual** [comment]
Closing issue.

If you need the AntiCheat enabled, then I recommend opening a ticket over at Impostor [here](https://github.com/Impostor/Impostor/issues).
