### ISSUE TITLE
Sheriff able to kill whilst having a Task open

### ISSUE THREAD

**Issue by C4KEfromSP4C3** [AJMix/TownOfImpostors#18]
It seems I was able to kill as Sheriff whilst on the filling gas task (Storage Gas, not one of the two engines). I'm unsure if I misclicked or if I was able to click the Shoot Button whilst in the task.

**Comment by AJMix** [comment]
Hey C4KE,

Thanks for playing the mod!

Thanks for reporting this - the ability to use buttons while having other windows (tasks, admin map, security cams etc.) open has been reported & will be fixed in the next release 🙂 

Best

**Comment by AJMix** [comment]
Issue fixed in 1.6.1. Please feel free to open another issue if this occurs again

Closing issue 👍
