### ISSUE TITLE
Impostor Comms

### ISSUE THREAD

**Issue by thegreatone5224** [AJMix/TownOfImpostors#20]
We had an issue plus a suggestion.

Issue: in the latest patch, even when impostor comms were turned off they were still used. Tried turning it on and back off but that didn't fix it.

Suggestion: When impostor comms are on, maybe turn it off for dead imposters so they can communicate with other dead people? Or make a toggle to choose between using one vs the other.

**Comment by MrFawkes1337** [comment]
It should be as simple as having a String for Enabled / Disabled, then checking the value of the string with if( ColorblindComms.GetText() == "Enabled")
{
    Run code here.
}

I dunno how the devs are doing it, but this is how I check it through my code. I run through HudManager.Update, and it works fine.

**Comment by AJMix** [comment]
Hey greatone,

Thanks for reporting the issue, it'll be fixed in the next release. The suggestion you mentioned is actually unintended and sounds like a bug so that'll be fixed too.

**Comment by AJMix** [comment]
Issues has been fixed in 1.7.0 release

Closing
