### ISSUE TITLE
Can't move after meeting/report.

### ISSUE THREAD

**Issue by Sotosleon** [AJMix/TownOfImpostors#22]
Pretty much the title. We were trying out the mod with 5 people and after the meeting we couldn't move. We could only move if we changed the resolution or changed Fullscreen option.

**Comment by Sotosleon** [comment]
Turns out it is fixxed by just opening the settings tab

**Comment by AJMix** [comment]
Hi Sotosleon,

Unfortunately, this is an Among Us issue in the latest Airship update and has nothing to do with this mod. I believe it's already been reported in the Among Us official discord.

Closing this issue
