### ISSUE TITLE
Airship - Avert Crash course

### ISSUE THREAD

**Issue by Niatuin** [AJMix/TownOfImpostors#23]
After installing this mod, the code to fix crash course sabotage on the Airship was always set to 00000.

**Comment by AJMix** [comment]
Hi Niatuin,

This sounds like a strange bug we've never encountered during testing. The crash course sabotage works fine from our testing.

Please double check:
- Has the mod been installed properly? Does everything else work?
- Did you use a Mod Manager to install? Are you also running other mods alongside this one?

Could you also send me your logs when you encounter this issue again. This can be found via the Among Us folder this mod is installed in, BepInEx folder -> LogOutput.log

**Comment by Niatuin** [comment]
We checked the other similar sabotage. (Comms on Mira) and didn't find something strange. Further did the Sabotage on Airship work again after we played on other maps. So far this only occured on one session, but then until we changed maps.

**Comment by JonyKasual** [comment]
Closing issue.

If it happens again, you may open another ticket and please attach LogOutput.log to that.
