### ISSUE TITLE
Mod Not Working On 2021.3.31s

### ISSUE THREAD

**Issue by zeldaking** [AJMix/TownOfImpostors#24]
I did everything right but the mod just won't load. I'm using the right version. Pls help!

**Comment by zeldaking** [comment]
I can add my log file. I hope this is it.
[LogOutput.log](https://github.com/AJMix/TownOfImpostors/files/6255550/LogOutput.log)

**Comment by AJMix** [comment]
Hey zeldaking,

Make sure the version is 2021.3.31.**3s**

The logs show that the wrong version of Among Us is being used with 1.7.0

Let me know how that goes for you

**Comment by JonyKasual** [comment]
Closing Issue.

Wrong version.
