### ISSUE TITLE
Among Us does not boot up with mod files installed

### ISSUE THREAD

**Issue by husaini657** [AJMix/TownOfImpostors#26]
Hi everyone,
I downloaded the mod files and extracted them into the steam local files of the game but it can't seem to run as it'll crash seconds after I try to run the .exe file. I have reinstalled Among Us a few times but the issue persists. The versions of both the mods and the game seems to be correct. Any help would be greatly appreciated 

[preloader_20210405_232632_773.log](https://github.com/AJMix/TownOfImpostors/files/6258972/preloader_20210405_232632_773.log)

[LogOutput.log](https://github.com/AJMix/TownOfImpostors/files/6258962/LogOutput.log)

**Comment by JonyKasual** [comment]
Hi,

It looks like you have another process running that is preventing the modded game from starting. I suggest restarting your computer. If you are able, you may also check through task manager to close the offending process.

If the issue persists, do you happen to have any antiviruses running?

**Comment by husaini657** [comment]
I paused my antivirus but it still doesn't seem to run. It should be that another process is running that is preventing the game from running but it's almost impossible to identify the specific program doing that. Do u have any other advice to help identify the program preventing the process from running? 

Thanks for the help so far!

**Comment by JonyKasual** [comment]
If you are willing, I'd start from scratch here. I suggest deleting/uninstalling all Among Us copies and installations, then re-downloaded and install a fresh unmodded clean version from Steam. Once you have done that, verify that this fresh copy works and that the version in the top left of the main menu reads exactly v2021.3.31.**3s** with nothing more or less than that. Close the game and restart your computer.

Once booted up, go through the installation steps again [here](https://github.com/AJMix/TownOfImpostors#installation). It sounds as though you have been modifying your original Among Us so far. We recommend that you make a full copy of that installation and mod the copy instead as Steam may auto-update and break the original installation. So ensure you follow the **"Copy ("Steam/steamapps/common/Among Us") to something like ("Steam/steamapps/common/Among Us Town Of Impostors")" and use the new folder** step.

**Comment by husaini657** [comment]
![image](https://user-images.githubusercontent.com/26163797/113715225-d3e76300-971b-11eb-86bc-abd6e6284c2a.png)

[preloader_20210406_210257_798.log](https://github.com/AJMix/TownOfImpostors/files/6266172/preloader_20210406_210257_798.log)

[LogOutput.log](https://github.com/AJMix/TownOfImpostors/files/6266177/LogOutput.log)


Alright, I followed your steps and made a copy of the game files at a new folder called Among Us town of imposters . I also verified that I have all the game folders according to the repo with the steam_appid.txt file too. The original issue is finally gone and the game can actually boot up with the mod files installed but the game mod does not show up thought. I came across a new problem in the logs saying that now apple.dll is already being used by another program

**Comment by JonyKasual** [comment]
Quick note to make sure you have no missing / corrupt cpp libs by installing [this](https://aka.ms/vs/16/release/vc_redist.x86.exe).

Then please give right clicking the Town Of Impostors Among Us.exe > Run as Administrator. It's unlikely to change anything, but worth a try.

If that all fails, the only other thing I can think of would be looking into adding exclusion rules for these files (perhaps the entire folder) in your antivirus or just outright disabling it (if you are comfortable with it). It's possible for the real-time scanning of your antivirus software to do this - and we really have to rule that out first as antiviruses are quite the prime suspect for causing these kinds of problems, some still have background processes scanning despite being 'paused'. 

If you have completely ruled out your antivirus, say by uninstalling and removing all operation of it, and the mod still doesn't run... well, I must apologise but that's as far as I can troubleshoot without starting on a long check of each process on your tasklist to see if its the culprit.

**Comment by JonyKasual** [comment]
Closing issue.

Haven't seen a response in a few days, so I hope things are fine. If you are still having trouble, I point you to our newly opened Discord server: https://discord.gg/xpsKVpUf4T
