### ISSUE TITLE
The custom hats don't show up in the hat menu.

### ISSUE THREAD

**Issue by ccir2429** [AJMix/TownOfImpostors#27]
I have the issue that the custom hats I added in the `TownOfImpostors_CustomHats` folder won't show up in-game. Is this a bug?
I made sure that they were .png and that they follow  the naming convention.

**Comment by AJMix** [comment]
Hey ccir,

Custom hats are only coming next release, I put instructions there along with the template so that people can start making their custom hats in preparation for next release.

I've edited the text stating this, to be bigger and more obvious

Closing issue

**Comment by ccir2429** [comment]
Thanks! I really thought that I made a mistake.
