### ISSUE TITLE
Better CrewLink: Players can hear dead after impostors die

### ISSUE THREAD

**Issue by FayneAldan** [AJMix/TownOfImpostors#31]
When both impostors die, BetterCrewLink thinks the game is over and allows everyone to talk. Not sure if this can be fixed in TOI but I thought I'd share it.

**Comment by JonyKasual** [comment]
That's probably a BetterCrewLink issue. I guess it's checking the number of live impostors to decide if the game is over? That would conflict with scenarios added by this mod where the game can continue with all dead impostors, e.g. game continues with live Arsonist.

**Comment by AJMix** [comment]
Hey Fayne,

Thanks for raising this issue. 

As mentioned by JonyKasual, it's probably better to raise an issue in the BetterCrewLink GitHub 🙂 

But I can maybe look into this specific case to see if I can potentially fix the issue on the ToI side of things

**Comment by OhMyGuus** [comment]
Hey, 

Just got notified about this issue and removed a check which should fix this. 
Sadly I don't have time to test & I don't play this mod too often, so if someone wants to test it here is the build: 
https://ci.appveyor.com/project/OhMyGuus/bettercrewlink/builds/38610616/job/2kh63g08q4o4uc2p/artifacts

Thanks in advance!

**Comment by JonyKasual** [comment]
Thanks OhMyGuus.

I'll leave the issue open for a while to see if anyone else can confirm the fix. But I'm sure it'll be fine, good work.

**Comment by AJMix** [comment]
Thanks OhMyGuus for getting a potential fix pushed for this so quickly 😄 

As mentioned by JonyKasual we'll leave this issue open and close it once we've properly tested

**Comment by OhMyGuus** [comment]
New version of BCL is released so this one can be closed now, sine it should be fixed 👍

**Comment by JonyKasual** [comment]
Some really overdue checking. Thanks OhMyGuus! Closing this.
