### ISSUE TITLE
Agent Cannot Remotely Access Cameras on Airship

### ISSUE THREAD

**Issue by drintath** [AJMix/TownOfImpostors#34]
Admin and Vitals are both accessible but Agent cannot use their remote Cams gadget on the new Airship map. I double-checked to make sure that the option was enabled in the settings menu, and I also tested to make sure that it was still working on other maps and the Camera gadget worked fine on both Skeld and Polus.

**Comment by JonyKasual** [comment]
Thanks for reporting this.

@AJMix has been informed and it will be fixed in the upcoming release.

**Comment by AJMix** [comment]
Fixed in 1.8.1 release.

Closing this issue
