### ISSUE TITLE
Camera gets blocked if a player is revived before the killing animation finished.

### ISSUE THREAD

**Issue by intDavid** [AJMix/TownOfImpostors#35]
If a Doctor revives the player while the killing animation is still ongoing the camera gets stuck to where the player was killed. The revived player can still move afterwards.

**Comment by AJMix** [comment]
Hey intDavid,

Thanks for reporting this edgecase bug, will look into it and hopefully get a fix in for it for next release

**Comment by AJMix** [comment]
Should be fixed in 1.8.1 release.

Closing this issue
