### ISSUE TITLE
cant move after a body is reported//emergency meeting

### ISSUE THREAD

**Issue by v1gg123** [AJMix/TownOfImpostors#36]
when a dead body is reported on version 1.8.1 players cannot move unless they toggle vsync, this isnt super high priority but it would still be nice to get a fix :)

**Comment by lazybobcat** [comment]
I think that's a bug with the game and not the mod. Hopefully it got fixed with today's update.

**Comment by JonyKasual** [comment]
Yes, it's a bug of the game at v2021.3.31.3s. You shouldn't have to toggle vsync, merely open up the settings and close it.

**Comment by AJMix** [comment]
As mentioned this is an Among Us bug :)

It appears to be fixed in the latest update of among us, closing this issue
