### ISSUE TITLE
Plumber cannot complete Download task in the lower left part of Airship

### ISSUE THREAD

**Issue by Khnum-Tohth** [AJMix/TownOfImpostors#39]
Hello,

As of this writing with version 1.8.6.1, I once played a game as plumber. One of my tasks was Download in the Viewing Deck (in the bottom left corner of the map). Unfortunately, the role's ability to vent had overridden the Use button in order to complete the task. Is it possible there might be a way to fix this issue? The crew would otherwise not be able to complete all tasks if even one of them is impossible to complete, regardless of the plumber's position relative to the task/vent (unless the plumber becomes a ghost).

**Comment by AJMix** [comment]
Hey Khnum,

Unfortunately due to how Plumber works, the "Vent" ability is prioritised for the "Use Button". 

The way around this is to actually click on the task itself with your mouse and that should allow you to open and do the task. Let me know how that works for you.

**Comment by AJMix** [comment]
Closing this issue.
