### ISSUE TITLE
Avatar incorrect on Jester win

### ISSUE THREAD

**Issue by neomis** [AJMix/TownOfImpostors#6]
When a Jester wins from being voted out.  Crewmates see the Impostor as the victor.  As the doctor I saw the correct avatar but no other custom roles were being used at the time

**Comment by AJMix** [comment]
Hi again!

Thanks for pointing out this issue to me, I'll be looking into it!

Thanks

**Comment by AJMix** [comment]
Fixed in 1.5 👍
