### ISSUE TITLE
Mod not working on Itch.io version

### ISSUE THREAD

**Issue by TheRandomHobo** [AJMix/TownOfImpostors#7]
Hi,
I've tried to run Among Us with this mod and it doesn't work. In main menu there isn't any info about mod under Among Us version number.

I'm using Itch.io verion of Among Us (ver. 2021.3.5i) with 1.4.0 version of Town of Impostors. 
Mod is installed according to instructions. I tried reinstalling vc_redist - still not working. Is it possible to run it on Itch.io version of Among Us or maybe I couldchange some setting in the mod files, so it will recognize other game version (I think itch "i" suffix in version number may be causing an error)? 

BepInEx\LogOutput.log content:

[Message: Preloader] BepInEx 6.0.0-reactor.16 - Among Us
[Message: Preloader] BLEEDING EDGE Build #16 from a44ed820546a57f00af344eb86ba879e270b71d3 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2019.4.9.5308042
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Town Of Impostors Mod 1.4.0]
[Error  :   BepInEx] Error loading [Town Of Impostors Mod 1.4.0] : Failure has occurred while loading a type.
[Message:   BepInEx] Chainloader startup complete

**Comment by AJMix** [comment]
Hey,

This mod is unfortunately not compatible with the itch.io version of Among Us, this is something that can't be changed unless I develop a version of the mod that is compatible with the itch.io version
