### ISSUE TITLE
Feature Request: Work with Unify mod

### ISSUE THREAD

**Issue by neomis** [AJMix/TownOfImpostors#8]
Thanks again for fixing the custom server code.  I've stumbled across this mod: https://github.com/MoltenMods/Unify and integrated it into other Among Us mods that have Custom Server issues.  Would it be possible to release a build of TownOfImpostors that doesn't mess with ` ServerManager.DefaultRegions`.  That way we can drop in the Unify.dll and have 1 system for controlling custom servers across mods.

Just a suggestion.  Keep up the good work.

**Comment by AJMix** [comment]
Hey Neo,

This can be looked into and will put an update here when I get a release of TownOfImpostors up that doesn't mess with `ServerManager.DefaultRegions` 👍

**Comment by AJMix** [comment]
Town Of Impostors no longer adjusts ServerManager from 1.6.0 onwards. Users are now directed to Unify mod in the README 👍 

Closing this issue.
