### ISSUE TITLE
Can't scroll down to options

### ISSUE THREAD

**Issue by NarfShaDoWs24** [AJMix/TownOfImpostors#9]
When I try to adjust game settings, it won't let me scroll down to past the general settings section. 

![Screenshot (1)](https://user-images.githubusercontent.com/79385797/111051317-63e10800-840f-11eb-968a-a45cc2ff68ee.png)

it will let me turn on or off that second option in general, but not anything past that

**Comment by AJMix** [comment]
Hi Narf,

I can see another mod has been loaded with this mod in this case.

If the installation instructions haven't been followed exactly, or you are using a mod manager or any other mods along with this mod, I cannot guarantee this mod will work as intended. (Mods can conflict with each other unfortunately).

If you've followed the installation instructions exactly, and you're only using this mod, and you're still experiencing this issue, please feel free to open another issue with screenshots attached
